import Head from 'next/head'
import MainTopbar from '../components/home/MainTopbar'


export default function Home() {
  return (
    <div className='w-[65%] h-[100%] bg-logo rounded-r-2xl'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <MainTopbar/>
    </div>
  )
}
