import Head from 'next/head'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <h2 className='text-7xl text-red-600 font-sans font-extrabold '>hello word</h2>
    </div>
  )
}
